### ISSUE TITLE
Column misalignment

### ISSUE THREAD

**Issue by campassi** [jimmoffitt/json2csv#1]
When performing a conversion using the 'everything' template, data seems to not be appearing in the correct location in the csv after column DZ. If I remove location{} and twitter_entities{symbols, urls, user_mentions, media} from the template all works fine again.

**Comment by campassi** [comment]
Any updates on this issue? Some serious misalignment errors are being encountered.. does GNIP plan to keep this tool supported? http://support.gnip.com/articles/json2csv.html

**Comment by jimmoffitt** [comment]
Thanks for pointing that out. No updates yet... This OSS sample code was put out there as a helper app, and never officially supported. However, I'll put it on the list to take a look....

**Comment by campassi** [comment]
Hey Jim, we ended up writing a python script to do the full conversion, no urgency from us as of this morning. Thank you for responding
